### ISSUE TITLE
react-timeline: Not Displaying Timeline

### ISSUE THREAD

**Issue by scscott12** [nanddeepn/code-samples#29]
I followed your directions but when I load to my workbench (gulp serve) i am unable to get the timeline to work on any of the sample timelines. The web part just says "configure your timeline".

Once i install the app in my app store on SharePoint i get the same error. I created a list in the same site as the timeline is deployed, I added the necessary columns to the list. select the list called "Timeline" and get the same error where the web part says "configure your timeline"

am i missing something?

![CropperCapture 26](https://user-images.githubusercontent.com/35305550/88096669-abebab80-cb5c-11ea-9bbe-8ff1ac944b44.jpg)

**Comment by nanddeepn** [comment]
Hi @scscott12 
Please check, if you can see any errors in the browser console. 
The final version of web part is available here: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-timeline

**Comment by scscott12** [comment]
I took your code from the latest version but did not see an easy way to
comment on the issue for your code specifically.

I get the following error.

GET
https://scscott12.sharepoint.com/sites/TrainingTestPage/_api/web/lists('d9f6ae3d-e704-4747-91f0-f34853d2979b')/items?$select=Id,Title,SPFxTimelineLink,SPFxTimelineDate,SPFxTimelinePicture,SPFxTimelineDescription&$orderby=SPFxTimelineDate%20desc
400

e.fetch @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
o @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
e.fetchRaw @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
v @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
e.fetch @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
e.send @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
r.value @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
ee @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
Promise.then (async)
r.value @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
ee @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
Promise.then (async)
r.value @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
ee @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
te @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
a @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
Promise.then (async)
l @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
v @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
_e @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
t.get @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
(anonymous) @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
Xr @ timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
e.getTimelineActivities @
timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
t.componentWillReceiveProps @
timeline-web-part_0c6b2e4df54aebf91a8080427c33653d.js:1
ql @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
aa @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
Oo @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
ko @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
bo @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
po @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
(anonymous) @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
CO/T.t.unstable_runWithPriority @
sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
dl @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
vl @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
ml @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
vo @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1
In @ sp-pages-assembly_en-us_d8697c0ab1abc48f9ca8f645a9c331b2.js:1

**Comment by nanddeepn** [comment]
Hi @scscott12 
What is the output you get in browser for below?

https://scscott12.sharepoint.com/sites/TrainingTestPage/_api/web/lists('d9f6ae3d-e704-4747-91f0-f34853d2979b')/items?$select=Id,Title,SPFxTimelineLink,SPFxTimelineDate,SPFxTimelinePicture,SPFxTimelineDescription&$orderby=SPFxTimelineDate%20desc

**Comment by scscott12** [comment]
This XML file does not appear to have any style information associated with
it. The document tree is shown below.
<m:error>
<m:code>-1, Microsoft.SharePoint.SPException</m:code>
<m:message xml:lang="en-US">
The field or property 'SPFxTimelineLink' does not exist.
</m:message>
</m:error>

**Comment by nanddeepn** [comment]
The error indicates the columns added to list should follow the pre-defined schema.
The schema is here: https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-timeline/sharepoint/assets/elements.xml

**Comment by scscott12** [comment]
Thank you for getting back to me.

I followed your directions on the list from here originally.
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-timeline#sharepoint-asset

I have now created 2 lists 1 named Timeline the other named Roadmap. I am
still not able to get them to show up.

[image: image.png]
[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by nanddeepn** [comment]
Sorry, I do not see the images you have posted.
Ideally the list should get created when you deploy the package to app catalog.
If it does not gets created, create with schema from elements.xml

**Comment by scscott12** [comment]
I got it to work. Thank you for getting back to me. You may want to add
that the names of the columns need to be:

Name="SPFxTimelineLink"
Name="SPFxTimelineDate"
Name="SPFxTimelinePicture"
Name="SPFxTimelineDescription"

Instead of (
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-timeline#sharepoint-asset
):

   - The "Title" column stores the event title.
   - The "Event Date" column represents the date of event.
   - The "Picture" column stores the url of image to be displayed for the
   event.
   - The "Link" column represents the url to event.
   - The "Description" column represents the more information about the
   event.
