### ISSUE TITLE
On Parent select, child items should auto select 

### ISSUE THREAD

**Issue by nanddeepn** [nanddeepn/code-samples#9]
An example here:
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeView/ItemSelectionAndCustomization/React/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeView/ItemSelectionAndCustomization/React/Light/)

**Comment by siddharth-vaghasia** [comment]
this is done and checked in
