### ISSUE TITLE
Bot is not giving any response

### ISSUE THREAD

**Issue by JAIS0N** [nanddeepn/code-samples#91]
Trying to debug test bot using teams test tool (preview) in VScode. No response, No errors 
<img width="955" alt="image" src="https://github.com/nanddeepn/code-samples/assets/46769916/bc4f5c2c-faa3-45a0-86c7-ced17aaa5cbd">

**Comment by nanddeepn** [comment]
Hi @JAIS0N 
Can you point to my code sample where you are facing this issue?

**Comment by JAIS0N** [comment]
> Hi @JAIS0N Can you point to my code sample where you are facing this issue?

Hi Mandeep thanks for the quick reply, didn't expect this, basically there is no error in code. Open AI and embedding imports appear to be deprecated. The issue is the bot doesn't reply. I referred code from your blog

**Comment by nanddeepn** [comment]
OK.
Can you please share the link to my blog where you referred this code from, to help me better understand ?

**Comment by JAIS0N** [comment]
> OK. Can you please share the link to my blog where you referred this code from, to help me better understand ?
I referred:
https://nanddeepnachanblogs.com/posts/2023-09-23-bring-own-data-teams-chatbot-azoai-langchain/

I also tried to print hello world as response after every step in code to determine the problem . Hello world is not getting printed after 




      const vectorStore = await MemoryVectorStore.fromDocuments(splitDocs, embeddings);

**Comment by nanddeepn** [comment]
Hi @JAIS0N 

Please use the code from [here](https://github.com/nanddeepn/code-samples/tree/master/MSTeams/teams-toolkit/azopenai-bot-langchain/langchainbot)

Use below to send message from bot to the user.
`
await context.sendActivity("YOUR MESSAGE");
`

**Comment by JAIS0N** [comment]
> Hi @JAIS0N
> 
> Please use the code from [here](https://github.com/nanddeepn/code-samples/tree/master/MSTeams/teams-toolkit/azopenai-bot-langchain/langchainbot)
> 
> Use below to send message from bot to the user. `await context.sendActivity("YOUR MESSAGE");`

This is working when hard-coded like this, I want to use open ai gpt 3 response as answer

**Comment by nanddeepn** [comment]
Please see line# 76 for your answer from this file:
https://github.com/nanddeepn/code-samples/blob/master/MSTeams/teams-toolkit/azopenai-bot-langchain/langchainbot/teamsBot.ts

**Comment by JAIS0N** [comment]
Using it as mentioned in the original blog, only difference is instead of teams on chrome or edge while.running  I am using test tool. Bot doesn't give any response

**Comment by nanddeepn** [comment]
Try debugging with VS Code to get more details.

**Comment by JAIS0N** [comment]
> Try debugging with VS Code via Debug menu to get more details.
> 
> ![image](https://private-user-images.githubusercontent.com/8310319/301948326-09e5bb8e-4f50-45d3-a302-2e44266e47d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDE5NzYsIm5iZiI6MTcwNjkwMTY3NiwicGF0aCI6Ii84MzEwMzE5LzMwMTk0ODMyNi0wOWU1YmI4ZS00ZjUwLTQ1ZDMtYTMwMi0yZTQ0MjY2ZTQ3ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTkyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdhZTZmMTcwODU1MzM1MWQ5NTczNThiMzhiYjliZjE4ZjNlZDNiYTE4ZWJmNWIyOTczZDlkODAzODEyYTAyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I5In-dYq-yZo07eP1ZuVxTJp28McMtS5R7EqPobiqDk)

Apart from deprication warnings there are no errors shown in debug console. I tried with both initial and latest code after deprication, issue is the same. Is this executable on your end via teams test tool?

**Comment by JAIS0N** [comment]
> Try debugging with VS Code via Debug menu to get more details.
> 
> ![image](https://private-user-images.githubusercontent.com/8310319/301948326-09e5bb8e-4f50-45d3-a302-2e44266e47d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDU4NTksIm5iZiI6MTcwNjk0NTU1OSwicGF0aCI6Ii84MzEwMzE5LzMwMTk0ODMyNi0wOWU1YmI4ZS00ZjUwLTQ1ZDMtYTMwMi0yZTQ0MjY2ZTQ3ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMDczMjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg0NjhlMTNlMWRjNDJlYmEwYTA2ZmNlOWQzMDZkNTQ1ZjFjMGJmZjEyMGZhNmI3YWExZjIzNzViNDk3ZjE5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n4pXjYz8fL5K3MkzbyxtMpgBiwzXIT2M2EgoMWx1NeE)

The error seems due to await chain.call() as call()  is deprecated, used invoke() still the same

**Comment by JAIS0N** [comment]
Hi @nanddeepn,

Thanks for your prompt and insightful responses on the issue I posted. It turns out the problem was on my end—I had entered the wrong instance name. 
Thank you once again for your patience and support. I truly appreciate your dedication to the community!
